schema_version: 1

context:
  name: newton
  version: "20260223"
  commit: 6256e0354ebb5560af9d64bc5727299da57b0f6f

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  git: https://github.com/newton-physics/newton.git
  rev: ${{ commit }}

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    # https://github.com/newton-physics/newton/blob/main/pyproject.toml
    - python >=${{ python_min }}
    - warp-lang >=1.11.0
    # [sim]
    - mujoco-warp >=3.5.0
    - mujoco >=3.5.0
    # [importers]
    - requests >=2.25.0
    - scipy
    - fast-simplification >=0.1.11
    - alphashape >=1.3.1
    - coacd >=1.0.7
    - trimesh >=4.6.8
    - pycollada >=0.9
    - resolve-robotics-uri-py >=0.4.0
    - openusd >=25.5
    - newton-usd-schemas >=0.1.0a2
    # [remesh]
    - open3d >=0.18.0
    - pyfqmr >=0.5.0
    # [examples]
    - pyglet >=2.1.6
    - gitpython >=3.1.44
    - imgui-bundle >=1.92.0
    - pyyaml >=6.0.2
    - cbor2 >=5.7.0
    # Other dependencies
    - importlib_resources
  run_constraints:
    - pytorch >=2.7.0

tests:
  - python:
      imports:
        - newton
      # Replaced with custom script below since pip check currently fails:
      # open3d-cpu 0.19.0+b53a3ad requires configargparse, which is not installed.
      # open3d-cpu 0.19.0+b53a3ad requires nbformat, which is not installed.
      # jaxlib 0.1.75 has requirement flatbuffers<3.0,>=1.12, but you have flatbuffers 25.9.23.
      pip_check: false
      python_version: ${{ python_min }}.*
  - script:
      - test $(pip check | grep newton | wc -l) -eq 0
    requirements:
      run:
        - pip
        - python ${{ python_min }}.*

about:
  homepage: https://newton-physics.github.io/newton/
  license: Apache-2.0
  license_file: LICENSE.md
  repository: https://github.com/newton-physics/newton
  summary: An open-source, GPU-accelerated physics simulation engine built upon NVIDIA Warp, specifically targeting roboticists and simulation researchers.

extra:
  recipe-maintainers:
    - diegoferigo
