schema_version: 1

context:
  name: mujoco-warp
  version: "3.5.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/mujoco_warp-${{ version }}.tar.gz
  sha256: 803a86569349e4abf7c7df3bcb2773ad78584c5f674ef56f515a510b9a996b30

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - absl-py
    - mujoco >=3.4.0
    - numpy
    - python >=${{ python_min }}
    - warp-lang >=1.11.0
    # etils[epath] dependencies.
    # https://github.com/google/etils/blob/main/pyproject.toml
    - etils
    - fsspec
    - typing-extensions
    - zipp

tests:
  - python:
      imports:
        - mujoco_warp
      pip_check: true
      # We should use python_min here, but on Python 3.10 a very old version of jaxlib is installed.
      python_version: 3.11.*
  - script:
      # The mujoco_warp package bundles the tests in the package, so we can run them from there.
      # We copy over the pyproject.toml to ensure that the upstream test configuration is used.
      - cwd=$(pwd) && cd $(python -c "import mujoco_warp; print(mujoco_warp.__path__[0])") && pytest --config-file "${cwd}/pyproject.toml"
    files:
      source:
        - pyproject.toml
    requirements:
      run:
        - pip
        - pytest
        - python 3.11.*
        # jax_test.py uses `scipy.linalg.tril`, which was removed in scipy 1.13.0.
        - scipy <1.13.0

about:
  homepage: https://github.com/google-deepmind/mujoco_warp
  license: Apache-2.0
  license_file: LICENSE
  repository: https://github.com/google-deepmind/mujoco_warp
  summary: GPU-optimized version of the MuJoCo physics simulator, designed for NVIDIA hardware.

extra:
  recipe-maintainers:
    - diegoferigo
    - oursland
    - traversaro
